ALTER TABLE `user` ADD COLUMN status VARCHAR(32) NULL;

UPDATE `user`
SET status = CASE WHEN is_active = TRUE THEN 'ACTIVE' ELSE 'DISABLED' END
WHERE status IS NULL;

ALTER TABLE `user` MODIFY status VARCHAR(32) NOT NULL;
