quarkus.application.name=notification-service
quarkus.http.port=${NOTIFICATION_SERVICE_PORT:8084}

mp.messaging.incoming.notification-commands-in.connector=smallrye-kafka
mp.messaging.incoming.notification-commands-in.topic=${KAFKA_NOTIFICATION_COMMANDS_TOPIC:javanc.notification.commands}
mp.messaging.incoming.notification-commands-in.group.id=${NOTIFICATION_KAFKA_GROUP_ID:notification-service-group}
mp.messaging.incoming.notification-commands-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.outgoing.notification-commands-dlq-out.connector=smallrye-kafka
mp.messaging.outgoing.notification-commands-dlq-out.topic=${KAFKA_NOTIFICATION_COMMANDS_DLQ_TOPIC:javanc.notification.commands.dlq}
mp.messaging.outgoing.notification-commands-dlq-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.datasource.db-kind=mysql
quarkus.hibernate-orm.log.sql=${NOTIFICATION_DB_LOG_SQL:false}

quarkus.rest-client.user-service.connect-timeout=${DOWNSTREAM_CONNECT_TIMEOUT:1000}
quarkus.rest-client.user-service.read-timeout=${DOWNSTREAM_READ_TIMEOUT:3000}
