quarkus.log.console.json.enabled=${LOG_JSON_ENABLED:true}
quarkus.micrometer.export.prometheus.enabled=${METRICS_PROMETHEUS_ENABLED:true}

messaging.enabled=${MESSAGING_ENABLED:false}
kafka.consumer.side-effects.enabled=${KAFKA_CONSUMER_SIDE_EFFECTS_ENABLED:false}
kafka.dlq.enabled=${KAFKA_DLQ_ENABLED:false}
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}
quarkus.kafka.devservices.enabled=${KAFKA_DEV_SERVICES_ENABLED:false}
mp.messaging.incoming.notification-commands-in.enabled=${MESSAGING_ENABLED:false}
mp.messaging.outgoing.notification-commands-dlq-out.enabled=${KAFKA_DLQ_ENABLED:false}

quarkus.datasource.username=${MYSQL_USERNAME}
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.jdbc.url=${NOTIFICATION_MYSQL_JDBC_URL}
quarkus.hibernate-orm.schema-management.strategy=${NOTIFICATION_DB_GENERATION:validate}

services.user.url=${USER_SERVICE_URL}
quarkus.rest-client.user-service.url=${USER_SERVICE_URL}
