quarkus.log.console.json.enabled=${LOG_JSON_ENABLED:true}
quarkus.micrometer.export.prometheus.enabled=${METRICS_PROMETHEUS_ENABLED:true}

messaging.enabled=${MESSAGING_ENABLED:false}
outbox.publisher.enabled=${OUTBOX_PUBLISHER_ENABLED:false}
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}
quarkus.kafka.devservices.enabled=${KAFKA_DEV_SERVICES_ENABLED:false}
mp.messaging.outgoing.project-events-out.enabled=${MESSAGING_ENABLED:false}
mp.messaging.outgoing.notification-commands-out.enabled=${MESSAGING_ENABLED:false}

quarkus.datasource.username=${MYSQL_USERNAME}
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.jdbc.url=${PROJECT_MYSQL_JDBC_URL}
quarkus.hibernate-orm.schema-management.strategy=${PROJECT_DB_GENERATION:validate}

services.image.url=${IMAGE_SERVICE_URL}
services.profile.url=${PROFILE_SERVICE_URL}
services.user.url=${USER_SERVICE_URL}
services.notification.url=${NOTIFICATION_SERVICE_URL}

quarkus.rest-client.image-service.url=${IMAGE_SERVICE_URL}
quarkus.rest-client.profile-service.url=${PROFILE_SERVICE_URL}
quarkus.rest-client.user-service.url=${USER_SERVICE_URL}
quarkus.rest-client.notification-service.url=${NOTIFICATION_SERVICE_URL}
