quarkus.log.console.json.enabled=${LOG_JSON_ENABLED:true}
quarkus.micrometer.export.prometheus.enabled=${METRICS_PROMETHEUS_ENABLED:true}

quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING}

services.user.url=${USER_SERVICE_URL}
services.image.url=${IMAGE_SERVICE_URL}
quarkus.rest-client.user-service.url=${USER_SERVICE_URL}
quarkus.rest-client.image-service.url=${IMAGE_SERVICE_URL}
