services.user.url=http://user-service.test
services.profile.url=http://profile-service.test
services.project.url=http://project-service.test
services.notification.url=http://notification-service.test
services.manager.url=http://manager-service.test
services.image.url=http://image-service.test
services.email.url=http://email-service.test
services.profile-hr.url=
gateway.auth.protected-prefixes=/users,/profiles,/project,/manager
