quarkus.application.name=gateway-service
quarkus.http.port=${GATEWAY_SERVICE_PORT:8080}

quarkus.log.category."com.javanc.gateway".level=${GATEWAY_LOG_LEVEL:DEBUG}

quarkus.http.cors.enabled=false
quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,origin,access-control-request-method,access-control-request-headers
quarkus.http.cors.exposed-headers=authorization,content-type
quarkus.http.cors.access-control-allow-credentials=true

gateway.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD
gateway.cors.headers=accept,authorization,content-type,x-requested-with,origin,access-control-request-method,access-control-request-headers
gateway.cors.exposed-headers=authorization,content-type

quarkus.http.limits.max-body-size=${GATEWAY_MAX_BODY_SIZE:20M}

gateway.auth.protected-prefixes=${GATEWAY_AUTH_PROTECTED_PREFIXES:/users,/profiles,/project,/manager}
gateway.request-timeout-millis=${GATEWAY_REQUEST_TIMEOUT_MILLIS:10000}
gateway.auth-timeout-millis=${GATEWAY_AUTH_TIMEOUT_MILLIS:5000}
