quarkus.mongodb.devservices.enabled=true
quarkus.mongodb.health.enabled=false
quarkus.mongodb.database=manager_service_test
messaging.enabled=false
outbox.publisher.enabled=false
quarkus.kafka.devservices.enabled=false
