quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:image_service_test;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false
quarkus.datasource.devservices.enabled=false
cloudinary.cloud-name=test-cloud
cloudinary.api-key=test-key
cloudinary.api-secret=test-secret
cloudinary.folder=javanc/test
