quarkus.log.console.json.enabled=${LOG_JSON_ENABLED:true}
quarkus.micrometer.export.prometheus.enabled=${METRICS_PROMETHEUS_ENABLED:true}

quarkus.datasource.username=${MYSQL_USERNAME}
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.jdbc.url=${IMAGE_MYSQL_JDBC_URL}
quarkus.hibernate-orm.schema-management.strategy=${IMAGE_DB_GENERATION:validate}

image.public-base-url=${IMAGE_PUBLIC_BASE_URL}
