quarkus.application.name=image-service
quarkus.http.port=${IMAGE_SERVICE_PORT:8083}

quarkus.datasource.db-kind=mysql
quarkus.hibernate-orm.log.sql=${IMAGE_DB_LOG_SQL:false}

quarkus.http.body.uploads-directory=${IMAGE_UPLOADS_DIR:target/uploads}
quarkus.http.limits.max-body-size=${IMAGE_MAX_BODY_SIZE:10M}
image.local-storage-dir=${IMAGE_LOCAL_STORAGE_DIR:target/uploads/public}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.folder=${CLOUDINARY_FOLDER:javanc}
