quarkus.log.console.json.enabled=${LOG_JSON_ENABLED:false}
quarkus.micrometer.export.prometheus.enabled=${METRICS_PROMETHEUS_ENABLED:true}

quarkus.datasource.username=${MYSQL_USERNAME:root}
quarkus.datasource.password=${MYSQL_PASSWORD:}
quarkus.datasource.jdbc.url=${IMAGE_MYSQL_JDBC_URL:jdbc:mysql://localhost:3307/image?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
quarkus.hibernate-orm.schema-management.strategy=${IMAGE_DB_GENERATION:update}

image.public-base-url=${IMAGE_PUBLIC_BASE_URL:http://localhost:8083}
