quarkus.log.console.json.enabled=${LOG_JSON_ENABLED:true}
quarkus.micrometer.export.prometheus.enabled=${METRICS_PROMETHEUS_ENABLED:true}

messaging.enabled=${MESSAGING_ENABLED:false}
kafka.consumer.side-effects.enabled=${KAFKA_CONSUMER_SIDE_EFFECTS_ENABLED:false}
kafka.dlq.enabled=${KAFKA_DLQ_ENABLED:false}
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}
quarkus.kafka.devservices.enabled=${KAFKA_DEV_SERVICES_ENABLED:false}
mp.messaging.incoming.email-commands-in.enabled=${MESSAGING_ENABLED:false}
mp.messaging.outgoing.email-commands-dlq-out.enabled=${KAFKA_DLQ_ENABLED:false}

quarkus.datasource.username=${MYSQL_USERNAME}
quarkus.datasource.password=${MYSQL_PASSWORD}
quarkus.datasource.jdbc.url=${EMAIL_MYSQL_JDBC_URL}
quarkus.hibernate-orm.schema-management.strategy=${EMAIL_DB_SCHEMA_STRATEGY:validate}

services.user.url=${USER_SERVICE_URL}
quarkus.rest-client.user-service.url=${USER_SERVICE_URL}

quarkus.mailer.host=${MAIL_HOST}
quarkus.mailer.port=${MAIL_PORT}
quarkus.mailer.username=${MAIL_USERNAME}
quarkus.mailer.password=${MAIL_PASSWORD}
quarkus.mailer.from=${MAIL_FROM}
quarkus.mailer.start-tls=${MAIL_START_TLS:REQUIRED}
quarkus.mailer.login=${MAIL_LOGIN:REQUIRED}
quarkus.mailer.mock=${MAIL_MOCK:false}
