quarkus.application.name=email-service
quarkus.http.port=${EMAIL_SERVICE_PORT:8087}

services.user.url=${USER_SERVICE_URL:http://localhost:8088}
quarkus.rest-client.user-service.url=${USER_SERVICE_URL:http://localhost:8088}

quarkus.mailer.host=${MAIL_HOST:smtp.gmail.com}
quarkus.mailer.port=${MAIL_PORT:587}
quarkus.mailer.username=${MAIL_USERNAME:}
quarkus.mailer.password=${MAIL_PASSWORD:}
quarkus.mailer.from=${MAIL_FROM:}
quarkus.mailer.start-tls=${MAIL_START_TLS:REQUIRED}
quarkus.mailer.login=${MAIL_LOGIN:REQUIRED}
quarkus.mailer.mock=${MAIL_MOCK:false}
mail.timeout-millis=${MAIL_TIMEOUT_MILLIS:5000}

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
email.kafka.group-id=${EMAIL_KAFKA_GROUP_ID:email-service-group}

%test.quarkus.mailer.mock=true
%test.quarkus.mailer.from=test@example.test
